-- V1__Initial_Schema.sql (Versión compatible con H2 y PostgreSQL)

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    max_players_per_team INTEGER NOT NULL DEFAULT 25,
    max_players_per_match INTEGER NOT NULL DEFAULT 18,
    yellow_cards_for_suspension INTEGER NOT NULL DEFAULT 5,
    max_trainings_per_week INTEGER NOT NULL DEFAULT 4,
    notify_before_match BOOLEAN NOT NULL DEFAULT TRUE,
    notify_before_training BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users(username)
);

CREATE TABLE season (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    start_date DATE,
    end_date DATE
);

CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    field VARCHAR(255),
    division VARCHAR(255),
    description VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    owner_id VARCHAR(255) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE opponent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    observations VARCHAR(255),
    team_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_opponent_team FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    opponent_id BIGINT NOT NULL,
    location VARCHAR(255),
    result VARCHAR(255),
    goals_for INTEGER,
    goals_against INTEGER,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    won BOOLEAN NOT NULL DEFAULT FALSE,
    draw BOOLEAN NOT NULL DEFAULT FALSE,
    finalized BOOLEAN NOT NULL DEFAULT FALSE,
    season_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_matches_opponent FOREIGN KEY (opponent_id) REFERENCES opponent(id),
    CONSTRAINT fk_matches_season FOREIGN KEY (season_id) REFERENCES season(id),
    CONSTRAINT fk_matches_team FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname_first VARCHAR(255) NOT NULL,
    surname_second VARCHAR(255),
    position VARCHAR(255) NOT NULL,
    number INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    team_id BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_player_team FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE player_match_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    goals INTEGER NOT NULL DEFAULT 0,
    assists INTEGER NOT NULL DEFAULT 0,
    minutes_played INTEGER NOT NULL DEFAULT 0,
    yellow_card BOOLEAN NOT NULL DEFAULT FALSE,
    double_yellow_card BOOLEAN NOT NULL DEFAULT FALSE,
    red_card BOOLEAN NOT NULL DEFAULT FALSE,
    goals_conceded INTEGER NOT NULL DEFAULT 0,
    own_goals INTEGER NOT NULL DEFAULT 0,
    called_up BOOLEAN NOT NULL DEFAULT FALSE,
    starter BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_stats_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_stats_player FOREIGN KEY (player_id) REFERENCES player(id),
    UNIQUE (match_id, player_id)
);

-- Las siguientes tablas son para futuras funcionalidades, las dejamos preparadas
CREATE TABLE injury (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT REFERENCES player(id),
    start_date DATE,
    estimated_end_date DATE,
    type VARCHAR(255),
    observations VARCHAR(255)
);

CREATE TABLE player_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT REFERENCES player(id),
    date DATE,
    amount DOUBLE PRECISION,
    description VARCHAR(255)
);

CREATE TABLE training (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP,
    location VARCHAR(255),
    training_type VARCHAR(255)
);

CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_id BIGINT REFERENCES training(id),
    player_id BIGINT REFERENCES player(id),
    observations VARCHAR(255)
);

CREATE TABLE team_expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    amount DOUBLE PRECISION,
    description VARCHAR(255)
);