-- Tablas sin dependencias externas
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE season (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    start_date DATE,
    end_date DATE
);

CREATE TABLE training (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP,
    location VARCHAR(255),
    training_type VARCHAR(255)
);

-- Tablas que dependen de 'users'
CREATE TABLE user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    max_players_per_team INT NOT NULL DEFAULT 25,
    max_players_per_match INT NOT NULL DEFAULT 18,
    yellow_cards_for_suspension INT NOT NULL DEFAULT 5,
    max_trainings_per_week INT NOT NULL DEFAULT 4,
    notify_before_match BOOLEAN NOT NULL DEFAULT TRUE,
    notify_before_training BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    field VARCHAR(255),
    division VARCHAR(255),
    description VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tablas que dependen de 'team'
CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname_first VARCHAR(255) NOT NULL,
    surname_second VARCHAR(255),
    position VARCHAR(255) NOT NULL,
    number INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    team_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE
);

CREATE TABLE opponent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    observations VARCHAR(255),
    team_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE
);

-- Tablas que dependen de 'players' y/u otras
CREATE TABLE injury (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE,
    estimated_end_date DATE,
    type VARCHAR(255),
    observations TEXT,
    player_id BIGINT NOT NULL,
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);

CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    location VARCHAR(255),
    result VARCHAR(255),
    goals_for INT,
    goals_against INT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    won BOOLEAN NOT NULL DEFAULT FALSE,
    draw BOOLEAN NOT NULL DEFAULT FALSE,
    finalized BOOLEAN NOT NULL DEFAULT FALSE,
    opponent_id BIGINT NOT NULL,
    season_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (opponent_id) REFERENCES opponent(id) ON DELETE CASCADE,
    FOREIGN KEY (season_id) REFERENCES season(id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE
);

-- Tabla con múltiples dependencias (la última)
CREATE TABLE player_match_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    goals INT NOT NULL DEFAULT 0,
    assists INT NOT NULL DEFAULT 0,
    minutes_played INT NOT NULL DEFAULT 0,
    yellow_card BOOLEAN NOT NULL DEFAULT FALSE,
    double_yellow_card BOOLEAN NOT NULL DEFAULT FALSE,
    red_card BOOLEAN NOT NULL DEFAULT FALSE,
    goals_conceded INT NOT NULL DEFAULT 0,
    own_goals INT NOT NULL DEFAULT 0,
    called_up BOOLEAN NOT NULL DEFAULT FALSE,
    starter BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_match_player UNIQUE (match_id, player_id),
    FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE,
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);