-- Tabla para configuraciones de tablas por usuario
CREATE TABLE table_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    page_size INT NOT NULL DEFAULT 10,
    default_sort_key VARCHAR(100),
    default_sort_order VARCHAR(10) NOT NULL DEFAULT 'ASC',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, table_name)
);

-- Tabla para configuraciones de columnas
CREATE TABLE table_column_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_configuration_id BIGINT NOT NULL,
    column_key VARCHAR(100) NOT NULL,
    column_label VARCHAR(100) NOT NULL,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    sortable BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT,
    width VARCHAR(50),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (table_configuration_id) REFERENCES table_configurations(id) ON DELETE CASCADE
);

-- Índices para mejorar rendimiento
CREATE INDEX idx_table_config_user_table ON table_configurations(user_id, table_name);
CREATE INDEX idx_column_config_table_id ON table_column_configurations(table_configuration_id);
CREATE INDEX idx_column_config_key ON table_column_configurations(column_key);
