-- =====================================================
-- MIGRACIÓN V3: Esquema de Ejercicios con Imágenes PNG
-- Compatible con PostgreSQL y H2
-- =====================================================

-- 1. CREAR TABLA DE EJERCICIOS CON CAMPO DE IMAGEN
CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000), -- Aumentado para más flexibilidad
    tactical_objectives VARCHAR(1000), -- Aumentado para más flexibilidad
    technical_objectives VARCHAR(1000), -- Aumentado para más flexibilidad
    physical_objectives VARCHAR(1000), -- Aumentado para más flexibilidad
    materials VARCHAR(1000), -- Aumentado para más flexibilidad
    category VARCHAR(50) NOT NULL,
    image_path VARCHAR(500), -- Campo para almacenar ruta de imagen PNG
    user_id BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 2. CREAR TABLA DE UNIÓN ENTRE ENTRENAMIENTOS Y EJERCICIOS
CREATE TABLE training_exercise (
    training_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    PRIMARY KEY (training_id, exercise_id),
    FOREIGN KEY (training_id) REFERENCES training(id) ON DELETE CASCADE,
    FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
);

-- 3. AÑADIR CAMPOS FALTANTES A LA TABLA TRAINING
-- Usar sintaxis estándar SQL compatible con ambos motores
ALTER TABLE training ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT 'Entrenamiento';
ALTER TABLE training ADD COLUMN session_number INTEGER NOT NULL DEFAULT 1;
ALTER TABLE training ADD COLUMN user_id BIGINT;
ALTER TABLE training ADD COLUMN deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE training ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE training ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 4. AÑADIR FOREIGN KEY PARA USER_ID EN TRAINING
ALTER TABLE training ADD CONSTRAINT fk_training_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- 5. CREAR ÍNDICES PARA MEJORAR RENDIMIENTO
-- Índices para exercises
CREATE INDEX idx_exercises_user_id ON exercises(user_id);
CREATE INDEX idx_exercises_category ON exercises(category);
CREATE INDEX idx_exercises_deleted ON exercises(deleted);
CREATE INDEX idx_exercises_title ON exercises(title);
CREATE INDEX idx_exercises_image_path ON exercises(image_path);

-- Índices para training
CREATE INDEX idx_training_user_id ON training(user_id);
CREATE INDEX idx_training_deleted ON training(deleted);
CREATE INDEX idx_training_title ON training(title);
CREATE INDEX idx_training_session_number ON training(session_number);
CREATE INDEX idx_training_exercise_training_id ON training_exercise(training_id);
CREATE INDEX idx_training_exercise_exercise_id ON training_exercise(exercise_id);

-- 6. AÑADIR FUNCIONALIDAD DE ASISTENCIA A ENTRENAMIENTOS

-- Añadir campo de observaciones a la tabla training
ALTER TABLE training ADD COLUMN observations VARCHAR(1000);

-- Añadir campo team_id a la tabla training
ALTER TABLE training ADD COLUMN team_id BIGINT NOT NULL DEFAULT 1;

-- Crear tabla de asistencia a entrenamientos
CREATE TABLE training_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    notes VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    
    FOREIGN KEY (training_id) REFERENCES training(id) ON DELETE CASCADE,
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX idx_training_attendance_training_id ON training_attendance(training_id);
CREATE INDEX idx_training_attendance_player_id ON training_attendance(player_id);
CREATE INDEX idx_training_attendance_status ON training_attendance(status);

-- Crear índice para el campo team_id en training
CREATE INDEX idx_training_team_id ON training(team_id);

-- Añadir restricción única para evitar duplicados de asistencia
ALTER TABLE training_attendance ADD CONSTRAINT uk_training_player UNIQUE (training_id, player_id);

-- 7. VERIFICAR LA MIGRACIÓN
-- Migración V3 completada exitosamente
-- Tabla exercises creada con estructura optimizada y campo image_path para imágenes PNG
-- Tabla training_exercise creada para entrenamientos
-- Tabla training_attendance creada para control de asistencia
-- Campos adicionales añadidos a training (title, session_number, observations, team_id)
-- Índices creados para optimizar rendimiento
-- COMPATIBLE CON: PostgreSQL y H2
-- FUNCIONALIDAD: Ejercicios con imágenes PNG, Entrenamientos con título y numeración automática
