# Configuración para el perfil 'desktop' - Aplicación de escritorio
server:
  port: 8081

spring:
  
  # Configuración de la base de datos
  datasource:
    url: jdbc:h2:file:${user.home}/.gestoteam/gestoteamdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  
  # Configuración de H2 Console (deshabilitada en producción)
  h2:
    console:
      enabled: false
  
  # Configuración de archivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Configuración de JWT - Valores por defecto para desktop
jwt:
  secret: "gestoteamDesktopSecretKey2024SecureAndValid"
  expiration: 86400

# Configuración de logging mejorada para desktop
logging:
  level:
    com.gestoteam: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${user.home}/.gestoteam/logs/gestoteam-desktop.log
    max-size: 10MB
    max-history: 30

# Configuración de CORS para aplicación de escritorio
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Configuración de almacenamiento de archivos
file:
  upload-dir: ${user.home}/.gestoteam/uploads
  max-size: 10MB

# Configuración específica para aplicación de escritorio
app:
  desktop:
    auto-start: true
    data-dir: ${user.home}/.gestoteam/data
    logs-dir: ${user.home}/.gestoteam/logs
    temp-dir: ${user.home}/.gestoteam/temp

# Configuración de Actuator para monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
